// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/services.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/services.go -destination=internal/core/ports/mocks/mock_services.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	domain "secure-payment-gateway/internal/core/domain"
	ports "secure-payment-gateway/internal/core/ports"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEncryptionService is a mock of EncryptionService interface.
type MockEncryptionService struct {
	ctrl     *gomock.Controller
	recorder *MockEncryptionServiceMockRecorder
	isgomock struct{}
}

// MockEncryptionServiceMockRecorder is the mock recorder for MockEncryptionService.
type MockEncryptionServiceMockRecorder struct {
	mock *MockEncryptionService
}

// NewMockEncryptionService creates a new mock instance.
func NewMockEncryptionService(ctrl *gomock.Controller) *MockEncryptionService {
	mock := &MockEncryptionService{ctrl: ctrl}
	mock.recorder = &MockEncryptionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEncryptionService) EXPECT() *MockEncryptionServiceMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *MockEncryptionService) Decrypt(ciphertext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", ciphertext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockEncryptionServiceMockRecorder) Decrypt(ciphertext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockEncryptionService)(nil).Decrypt), ciphertext)
}

// Encrypt mocks base method.
func (m *MockEncryptionService) Encrypt(plaintext string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", plaintext)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockEncryptionServiceMockRecorder) Encrypt(plaintext any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockEncryptionService)(nil).Encrypt), plaintext)
}

// MockSignatureService is a mock of SignatureService interface.
type MockSignatureService struct {
	ctrl     *gomock.Controller
	recorder *MockSignatureServiceMockRecorder
	isgomock struct{}
}

// MockSignatureServiceMockRecorder is the mock recorder for MockSignatureService.
type MockSignatureServiceMockRecorder struct {
	mock *MockSignatureService
}

// NewMockSignatureService creates a new mock instance.
func NewMockSignatureService(ctrl *gomock.Controller) *MockSignatureService {
	mock := &MockSignatureService{ctrl: ctrl}
	mock.recorder = &MockSignatureServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSignatureService) EXPECT() *MockSignatureServiceMockRecorder {
	return m.recorder
}

// BuildCanonicalString mocks base method.
func (m *MockSignatureService) BuildCanonicalString(method, path string, timestamp int64, nonce, body string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildCanonicalString", method, path, timestamp, nonce, body)
	ret0, _ := ret[0].(string)
	return ret0
}

// BuildCanonicalString indicates an expected call of BuildCanonicalString.
func (mr *MockSignatureServiceMockRecorder) BuildCanonicalString(method, path, timestamp, nonce, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildCanonicalString", reflect.TypeOf((*MockSignatureService)(nil).BuildCanonicalString), method, path, timestamp, nonce, body)
}

// Sign mocks base method.
func (m *MockSignatureService) Sign(secretKey, payload string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sign", secretKey, payload)
	ret0, _ := ret[0].(string)
	return ret0
}

// Sign indicates an expected call of Sign.
func (mr *MockSignatureServiceMockRecorder) Sign(secretKey, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sign", reflect.TypeOf((*MockSignatureService)(nil).Sign), secretKey, payload)
}

// Verify mocks base method.
func (m *MockSignatureService) Verify(secretKey, payload, signature string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", secretKey, payload, signature)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Verify indicates an expected call of Verify.
func (mr *MockSignatureServiceMockRecorder) Verify(secretKey, payload, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockSignatureService)(nil).Verify), secretKey, payload, signature)
}

// MockHashService is a mock of HashService interface.
type MockHashService struct {
	ctrl     *gomock.Controller
	recorder *MockHashServiceMockRecorder
	isgomock struct{}
}

// MockHashServiceMockRecorder is the mock recorder for MockHashService.
type MockHashServiceMockRecorder struct {
	mock *MockHashService
}

// NewMockHashService creates a new mock instance.
func NewMockHashService(ctrl *gomock.Controller) *MockHashService {
	mock := &MockHashService{ctrl: ctrl}
	mock.recorder = &MockHashServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHashService) EXPECT() *MockHashServiceMockRecorder {
	return m.recorder
}

// Hash mocks base method.
func (m *MockHashService) Hash(password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *MockHashServiceMockRecorder) Hash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*MockHashService)(nil).Hash), password)
}

// Verify mocks base method.
func (m *MockHashService) Verify(password, hash string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", password, hash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockHashServiceMockRecorder) Verify(password, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockHashService)(nil).Verify), password, hash)
}

// MockTokenService is a mock of TokenService interface.
type MockTokenService struct {
	ctrl     *gomock.Controller
	recorder *MockTokenServiceMockRecorder
	isgomock struct{}
}

// MockTokenServiceMockRecorder is the mock recorder for MockTokenService.
type MockTokenServiceMockRecorder struct {
	mock *MockTokenService
}

// NewMockTokenService creates a new mock instance.
func NewMockTokenService(ctrl *gomock.Controller) *MockTokenService {
	mock := &MockTokenService{ctrl: ctrl}
	mock.recorder = &MockTokenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenService) EXPECT() *MockTokenServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockTokenService) Generate(merchantID uuid.UUID, accessKey string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", merchantID, accessKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Generate indicates an expected call of Generate.
func (mr *MockTokenServiceMockRecorder) Generate(merchantID, accessKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockTokenService)(nil).Generate), merchantID, accessKey)
}

// Validate mocks base method.
func (m *MockTokenService) Validate(tokenString string) (*ports.TokenClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", tokenString)
	ret0, _ := ret[0].(*ports.TokenClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Validate indicates an expected call of Validate.
func (mr *MockTokenServiceMockRecorder) Validate(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTokenService)(nil).Validate), tokenString)
}

// MockIdempotencyCache is a mock of IdempotencyCache interface.
type MockIdempotencyCache struct {
	ctrl     *gomock.Controller
	recorder *MockIdempotencyCacheMockRecorder
	isgomock struct{}
}

// MockIdempotencyCacheMockRecorder is the mock recorder for MockIdempotencyCache.
type MockIdempotencyCacheMockRecorder struct {
	mock *MockIdempotencyCache
}

// NewMockIdempotencyCache creates a new mock instance.
func NewMockIdempotencyCache(ctrl *gomock.Controller) *MockIdempotencyCache {
	mock := &MockIdempotencyCache{ctrl: ctrl}
	mock.recorder = &MockIdempotencyCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIdempotencyCache) EXPECT() *MockIdempotencyCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockIdempotencyCache) Get(ctx context.Context, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIdempotencyCacheMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIdempotencyCache)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockIdempotencyCache) Set(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockIdempotencyCacheMockRecorder) Set(ctx, key, value, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockIdempotencyCache)(nil).Set), ctx, key, value, ttl)
}

// MockNonceStore is a mock of NonceStore interface.
type MockNonceStore struct {
	ctrl     *gomock.Controller
	recorder *MockNonceStoreMockRecorder
	isgomock struct{}
}

// MockNonceStoreMockRecorder is the mock recorder for MockNonceStore.
type MockNonceStoreMockRecorder struct {
	mock *MockNonceStore
}

// NewMockNonceStore creates a new mock instance.
func NewMockNonceStore(ctrl *gomock.Controller) *MockNonceStore {
	mock := &MockNonceStore{ctrl: ctrl}
	mock.recorder = &MockNonceStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNonceStore) EXPECT() *MockNonceStoreMockRecorder {
	return m.recorder
}

// CheckAndSet mocks base method.
func (m *MockNonceStore) CheckAndSet(ctx context.Context, merchantID, nonce string, ttl time.Duration) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAndSet", ctx, merchantID, nonce, ttl)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAndSet indicates an expected call of CheckAndSet.
func (mr *MockNonceStoreMockRecorder) CheckAndSet(ctx, merchantID, nonce, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAndSet", reflect.TypeOf((*MockNonceStore)(nil).CheckAndSet), ctx, merchantID, nonce, ttl)
}

// MockPaymentService is a mock of PaymentService interface.
type MockPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceMockRecorder
	isgomock struct{}
}

// MockPaymentServiceMockRecorder is the mock recorder for MockPaymentService.
type MockPaymentServiceMockRecorder struct {
	mock *MockPaymentService
}

// NewMockPaymentService creates a new mock instance.
func NewMockPaymentService(ctrl *gomock.Controller) *MockPaymentService {
	mock := &MockPaymentService{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentService) EXPECT() *MockPaymentServiceMockRecorder {
	return m.recorder
}

// ProcessPayment mocks base method.
func (m *MockPaymentService) ProcessPayment(ctx context.Context, req ports.PaymentRequest) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessPayment", ctx, req)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessPayment indicates an expected call of ProcessPayment.
func (mr *MockPaymentServiceMockRecorder) ProcessPayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessPayment", reflect.TypeOf((*MockPaymentService)(nil).ProcessPayment), ctx, req)
}

// ProcessRefund mocks base method.
func (m *MockPaymentService) ProcessRefund(ctx context.Context, req ports.RefundRequest) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessRefund", ctx, req)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessRefund indicates an expected call of ProcessRefund.
func (mr *MockPaymentServiceMockRecorder) ProcessRefund(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessRefund", reflect.TypeOf((*MockPaymentService)(nil).ProcessRefund), ctx, req)
}

// ProcessTopup mocks base method.
func (m *MockPaymentService) ProcessTopup(ctx context.Context, req ports.TopupRequest) (*domain.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTopup", ctx, req)
	ret0, _ := ret[0].(*domain.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProcessTopup indicates an expected call of ProcessTopup.
func (mr *MockPaymentServiceMockRecorder) ProcessTopup(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTopup", reflect.TypeOf((*MockPaymentService)(nil).ProcessTopup), ctx, req)
}

// MockAuthService is a mock of AuthService interface.
type MockAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockAuthServiceMockRecorder
	isgomock struct{}
}

// MockAuthServiceMockRecorder is the mock recorder for MockAuthService.
type MockAuthServiceMockRecorder struct {
	mock *MockAuthService
}

// NewMockAuthService creates a new mock instance.
func NewMockAuthService(ctrl *gomock.Controller) *MockAuthService {
	mock := &MockAuthService{ctrl: ctrl}
	mock.recorder = &MockAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthService) EXPECT() *MockAuthServiceMockRecorder {
	return m.recorder
}

// Login mocks base method.
func (m *MockAuthService) Login(ctx context.Context, username, password string) (string, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, username, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Login indicates an expected call of Login.
func (mr *MockAuthServiceMockRecorder) Login(ctx, username, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockAuthService)(nil).Login), ctx, username, password)
}

// Register mocks base method.
func (m *MockAuthService) Register(ctx context.Context, req ports.RegisterRequest) (*ports.RegisterResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, req)
	ret0, _ := ret[0].(*ports.RegisterResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockAuthServiceMockRecorder) Register(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockAuthService)(nil).Register), ctx, req)
}

// MockReportingService is a mock of ReportingService interface.
type MockReportingService struct {
	ctrl     *gomock.Controller
	recorder *MockReportingServiceMockRecorder
	isgomock struct{}
}

// MockReportingServiceMockRecorder is the mock recorder for MockReportingService.
type MockReportingServiceMockRecorder struct {
	mock *MockReportingService
}

// NewMockReportingService creates a new mock instance.
func NewMockReportingService(ctrl *gomock.Controller) *MockReportingService {
	mock := &MockReportingService{ctrl: ctrl}
	mock.recorder = &MockReportingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReportingService) EXPECT() *MockReportingServiceMockRecorder {
	return m.recorder
}

// GetDashboardStats mocks base method.
func (m *MockReportingService) GetDashboardStats(ctx context.Context, merchantID uuid.UUID, period string) (*ports.TransactionStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDashboardStats", ctx, merchantID, period)
	ret0, _ := ret[0].(*ports.TransactionStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDashboardStats indicates an expected call of GetDashboardStats.
func (mr *MockReportingServiceMockRecorder) GetDashboardStats(ctx, merchantID, period any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDashboardStats", reflect.TypeOf((*MockReportingService)(nil).GetDashboardStats), ctx, merchantID, period)
}

// GetWalletBalance mocks base method.
func (m *MockReportingService) GetWalletBalance(ctx context.Context, merchantID uuid.UUID) (int64, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWalletBalance", ctx, merchantID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetWalletBalance indicates an expected call of GetWalletBalance.
func (mr *MockReportingServiceMockRecorder) GetWalletBalance(ctx, merchantID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWalletBalance", reflect.TypeOf((*MockReportingService)(nil).GetWalletBalance), ctx, merchantID)
}

// ListTransactions mocks base method.
func (m *MockReportingService) ListTransactions(ctx context.Context, params ports.TransactionListParams) ([]domain.Transaction, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransactions", ctx, params)
	ret0, _ := ret[0].([]domain.Transaction)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListTransactions indicates an expected call of ListTransactions.
func (mr *MockReportingServiceMockRecorder) ListTransactions(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransactions", reflect.TypeOf((*MockReportingService)(nil).ListTransactions), ctx, params)
}

// MockWebhookService is a mock of WebhookService interface.
type MockWebhookService struct {
	ctrl     *gomock.Controller
	recorder *MockWebhookServiceMockRecorder
	isgomock struct{}
}

// MockWebhookServiceMockRecorder is the mock recorder for MockWebhookService.
type MockWebhookServiceMockRecorder struct {
	mock *MockWebhookService
}

// NewMockWebhookService creates a new mock instance.
func NewMockWebhookService(ctrl *gomock.Controller) *MockWebhookService {
	mock := &MockWebhookService{ctrl: ctrl}
	mock.recorder = &MockWebhookServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWebhookService) EXPECT() *MockWebhookServiceMockRecorder {
	return m.recorder
}

// EnqueueWebhook mocks base method.
func (m *MockWebhookService) EnqueueWebhook(ctx context.Context, transaction *domain.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnqueueWebhook", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnqueueWebhook indicates an expected call of EnqueueWebhook.
func (mr *MockWebhookServiceMockRecorder) EnqueueWebhook(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnqueueWebhook", reflect.TypeOf((*MockWebhookService)(nil).EnqueueWebhook), ctx, transaction)
}
